[package]
name = "cairo-lang-reader"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro = "0.1.1"
cairo-lang-parser = "2.9.2"
cairo-lang-syntax = "2.9.2"
cairo-lang-defs = "2.9.2"
cairo-lang-diagnostics = "2.9.2"
cairo-lang-filesystem = "2.9.2"
smol_str = "0.2.2"

[workspace]
