[package]
name = "cairo_lang_reader"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
cairo-lang-macro = "0.1.1"
cairo-lang-parser = "2.10.1"
cairo-lang-syntax = "2.10.1"
cairo-lang-defs = "2.10.1"
cairo-lang-diagnostics = "2.10.1"
cairo-lang-filesystem = "2.10.1"
smol_str = "0.2.2"
